### ISSUE TITLE
Firefox and IE

### ISSUE THREAD

**Issue by saynala** [YahooArchive/boomerang#6]
I have seen different o.t_load, o.bw and o.lat values in IE and FF. Am I doing anything wrong?

**Comment by bluesmoon** [comment]
how different are the values and are they consistent?  It could just be network jitter.

**Comment by saynala** [comment]
Here are the results:

FF:
This page took 1841ms to load
Your bandwidth to this server is 10612kbps (±17%)
Your latency to this server is 17±1.96ms

IE:
This page took 1617ms to load
Your bandwidth to this server is 37275kbps (±12%)
Your latency to this server is 17±4.1ms

Thanks

**Comment by bluesmoon** [comment]
Which versions of IE and FF are these?  IE 7 and below do not download scripts in parallel while FF 2 and above do, and this could significantly affect page load time.  Differences in bandwidth are probably because of network jitter or something else that was being downloaded at that time.  It could also happen if both tests were run in parallel.

**Comment by saynala** [comment]
Versions:
FF : 3.6.13 and IE : 7.0.6. I think the parallel processing in FF explains the difference in page load time.

Tests were run one after the other on same machine.

**Comment by bluesmoon** [comment]
closing
